mysql:
 host: "127.0.0.1"
 port: "3306"
 username: "root"
 password: "card9033"
 dbName: "sobbleweb"  
 
jwt:
  signkey: "cyansobblesunflower"
  expiretime: "7d"
  issuer: "cyan"
  audience: "cyans"

local:
  path: "upload/file"

email:
  username: "purepoison77@yeah.net"
  password: "LLFDBKVLCLHULPJW"
  host: "smtp.yeah.net"
  port: "25"

redis:
  host: "localhost"
  port: "6379"
  user: ""
  password: ""
  db: "0"