mysql:
 host: "127.0.0.1"
 port: "3306"
 username: "root"
 password: "card9033"
 dbName: "cyanweb"  
 
jwt:
  signkey: "cyansobblesunflower"
  expiretime: "7d"
  issuer: "cyan"
  audience: "cyans"

local:
  path: "upload/file"